apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admissionwebhook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admissionwebhook.name" . }}
    helm.sh/chart: {{ include "admissionwebhook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "admissionwebhook.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "admissionwebhook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: webhook-tls
          secret:
            secretName: {{ include "admissionwebhook.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.container.envVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: webhook-tls
              mountPath: {{ .Values.tls.mountPaths.key }}
              subPath: key.pem
              readOnly: true
            - name: webhook-tls
              mountPath: {{ .Values.tls.mountPaths.cert }}
              subPath: cert.pem
              readOnly: true
          ports:
            - name: https
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          {{- if ne "" .Values.api.health }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: {{ .Values.api.health }}
              port: https
            initialDelaySeconds: 15
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
