apiVersion: v1
kind: Service
metadata:
  name: {{ include "admissionwebhook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "admissionwebhook.name" . }}
    helm.sh/chart: {{ include "admissionwebhook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "admissionwebhook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
