apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: admissionwebhooks.admissionwebhookoperator.k8s.io
spec:
  group: admissionwebhookoperator.k8s.io
  names:
    kind: AdmissionWebhook
    listKind: AdmissionWebhookList
    plural: admissionwebhooks
    singular: admissionwebhook
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  # validation:
  #   # openAPIV3Schema is the schema for validating custom objects.
  #   openAPIV3Schema:
  #     properties:
  #       spec:
  #         properties:
  #           myCrdField:
  #             type: string
  #             pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
  #           anotherCrdField:
  #             type: integer
  #             minimum: 1
  #             maximum: 10
  additionalPrinterColumns:
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
