apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: admissionwebhooks.admissionwebhookoperator.k8s.io
spec:
  group: admissionwebhookoperator.k8s.io
  names:
    kind: AdmissionWebhook
    listKind: AdmissionWebhookList
    plural: admissionwebhooks
    singular: admissionwebhook
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
