# Default values for admissionwebhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

api:
  # Admission webhook apis must respond to HTTPS (a cert and key are mounted into the
  # container for use, see below)
  port: 443
  path: /
  # If specified, an HTTP GET liveness probe will be directed at this path
  health: ""

tls:
  mountPaths:
    cert: &tlsCertPath /cert.pem
    key: &tlsKeyPath /key.pem

container:
  envVars:
    - name: PASSENGER_PORT
      value: "443"
    - name: PASSENGER_SSL
      value: "true"
    - name: PASSENGER_SSL_CERTIFICATE
      value: *tlsCertPath
    - name: PASSENGER_SSL_CERTIFICATE_KEY
      value: *tlsKeyPath

webhookConfiguration:
  rules:
    - operations: ["CREATE","UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  failurePolicy: Ignore
  namespaceSelector:
    # Will default to `admissionwebhook/<name>: enabled`
    matchLabels:

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
